import logo from "./images/Logo.png";
import logout from "./images/log-out-04.png";
import homeIcon from "./images/home-04.png";
import settings from "./images/settings-01.png";
import phone from "./images/phone.png";
import video from "./images/video-recorder.png";
import profilePicture from "./images/profile-picture.png";
import searchIcon from "./images/search-sm.png";
import person3 from "./images/Picture3.png";
import person4 from "./images/Picture4.png";
import person5 from "./images/Picture5.png";
import person6 from "./images/Picture6.png";
import person7 from "./images/Picture7.png";
import person8 from "./images/Picture8.png";
import person9 from "./images/Picture9.png";
import person10 from "./images/Picture10.png";
import person11 from "./images/Picture11.png";
import online from "./images/online.png";
import offline from "./images/offline.png";
import optionsChat from "./images/optionsChat.png";
import videoChat from "./images/videoChat.png";
import phoneChat from "./images/phoneChat.png";
import chatIcon from "./images/chat-icon.png";
import chatIcon2 from "./images/chat-icon2.png";
import sendDocs from "./images/send-doc.png";
import sendPics from "./images/send-pics.png";
import voiceNote from "./images/voice-note.png";
import sendIcon from "./images/send-icon.png";
import uploadPicture from "./images/upload-picture.png";
import pdfLogo from "./images/pdf-logo.png";
import closeUploadPics from "./images/x-square.png";
import deleteUploadPics from "./images/trash-03.png";
import rotateImage from "./images/refresh-cw-01.png";
import uploadedPics from "./images/uploaded-pics.png";
import uploadedFile from "./images/uploaded-file.png";
import microphoneBlue from "./images/microphone-01.png";
import recordingStop from "./images/recording stop.png";
import caller from "./images/caller.png";
import endCall from "./images/end-call.png";
import chatMedia1 from "./images/chat-media-1.png";
import chatMedia2 from "./images/chat-media-2.png";
import chatMedia3 from "./images/chat-media-3.png";
import chatMedia4 from "./images/chat-media-4.png";
import chatMedia5 from "./images/chat-media-5.png";
import pdfIcon from "./images/pdfLogo.png";
import pptLogo from "./images/pptLogo.png";
import xlsLogo from "./images/xlsLogo.png";
import docLogo from "./images/docLogo.png";
import imagePlaceholder from "./images/image-placeholder.png";
import videoPlaceholder from "./images/video-placeholder.png";
import voiceNotePlaceholder from "./images/voice-note-placeholder.png";
import subtract from "./images/Subtract.png";
import videoCall from "./images/video-call.gif";

export const Logo = logo;
export const Logout = logout;
export const HomeIcon = homeIcon;
export const Settings = settings;
export const Phone = phone;
export const Video = video;
export const ProfilePicture = profilePicture;
export const SearchIcon = searchIcon;
export const Person3 = person3;
export const Person4 = person4;
export const Person5 = person5;
export const Person6 = person6;
export const Person7 = person7;
export const Person8 = person8;
export const Person9 = person9;
export const Person10 = person10;
export const Person11 = person11;
export const Online = online;
export const Offline = offline;
export const OptionsChat = optionsChat;
export const VideoChat = videoChat;
export const PhoneChat = phoneChat;
export const ChatIcon = chatIcon;
export const ChatIcon2 = chatIcon2;
export const SendDocs = sendDocs;
export const SendPics = sendPics;
export const VoiceNote = voiceNote;
export const SendIcon = sendIcon;
export const UploadPicture = uploadPicture;
export const PdfLogo = pdfLogo;
export const RotateImage = rotateImage;
export const CloseUploadPics = closeUploadPics;
export const DeleteUploadPics = deleteUploadPics;
export const UploadedPics = uploadedPics;
export const UploadedFile = uploadedFile;
export const MicrophoneBlue = microphoneBlue;
export const RecordingStop = recordingStop;
export const Caller = caller;
export const EndCall = endCall;
export const VideoCall = videoCall;
export const ChatMedia1 = chatMedia1;
export const ChatMedia2 = chatMedia2;
export const ChatMedia3 = chatMedia3;
export const ChatMedia4 = chatMedia4;
export const ChatMedia5 = chatMedia5;
export const PdfIcon = pdfIcon;
export const PptLogo = pptLogo;
export const XlsLogo = xlsLogo;
export const DocLogo = docLogo;
export const ImagePlaceholder = imagePlaceholder;
export const VideoPlaceholder = videoPlaceholder;
export const VoiceNotePlaceholder = voiceNotePlaceholder;
export const Subtract = subtract;
